// shopify.app.toml
name = "Product Icon App"
client_id = "your_client_id_here"
application_url = "https://your-app-url.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://your-app-url.com/auth/callback"
]

[webhooks]
api_version = "2023-10"